GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzEyMjQ5NTY2LCJleHAiOjE3MTIyNDk1ODF9.9sIK1GkU6qPA5tN5pcZw7ioSs0d9nDiFavUPaQOiKok

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzEyMjQ5NTIyfQ.wc97tSSVzG89GEjWr85JM1yFjjh5Bs8QSphkiE_rOGE"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}